export BUILT_PRODUCTS_DIR="/Users/Apostolis/Library/Developer/Xcode/DerivedData/tumitfahrer-dgdsaqwcqfmwukatctamxhluunkn/Build/Products/Release-iphonesimulator"
export CURRENT_ARCH="x86_64"
export OBJECT_FILE_DIR_normal="/Users/Apostolis/Library/Developer/Xcode/DerivedData/tumitfahrer-dgdsaqwcqfmwukatctamxhluunkn/Build/Intermediates/tumitfahrer.build/Release-iphonesimulator/mitfahrer-app.build/Objects-normal"
export OBJROOT="/Users/Apostolis/Library/Developer/Xcode/DerivedData/tumitfahrer-dgdsaqwcqfmwukatctamxhluunkn/Build/Intermediates"
export SRCROOT="/Users/Apostolis/Desktop/tumitfahrer-ios--opensource"
